server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEBEMBEDDED
      - WEB
      - TVHTML5EMBEDDED
      - ANDROID_MUSIC
      - IOS
    clientOptions:
      MUSIC:
        searching: false
      ANDROID_VR:
        searching: false
      WEBEMBEDDED:
        searching: false
      WEB:
        searching: true
      TVHTML5EMBEDDED:
        searching: false
      ANDROID_MUSIC:
        searching: false
      IOS:
        searching: false

